# PART 1 : ONLY DIRTY WORK

### YOU CAN FIND ME OCCASSIONALLY SAVING STUFF TO CSV. THIS IS BECAUSE, I DONT WANT TO RUN THE WHOLE CODE SNIPPET TO REACH MY CURRENT POSITION.

### I CAN JUMP TO THE STARTING POINT DIRECTLY.

## Webscraping

In [ ]:
import requests
from bs4 import BeautifulSoup

# Send a GET request to the URL
url = 'https://keylessonline.com/song/carnatic/karn/Varaveena_Geetham_Mohanam.html'
response = requests.get(url)

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Extract all the text from the webpage and split it by newline characters
text = soup.get_text()
lines = text.split('\n')

# Remove any empty lines from the list and replace non-breaking space characters and hyphens
lines = [line.replace('\xa0', ' ').replace('-', '').strip() for line in lines if line.strip()]

# Print each line on a new line
for line in lines:
    print(line)

Varaveena Geetham Mohanam Carnatic Carnatic Notes
KeyLess Online
Home
Song Notes
Tamil
Hindi
Telugu
Kannada
Malayalam
Kids Corner
Carnatic
Misc
Devotional
English
Punjabi
Marathi
Western Theory
RequestASong
Legend
FAQ
External Links
Pallavi Music Group
Sankara Eye Foundation
Sankara Nethralaya
Enter your search terms
Submit search form
News
KeyLess Online Facebook Page
September 26, 2016Like the facebook page to get notified on new song posts
KeyLess Online Twitter Feed
November 2, 2016Follow twitter handle @keylessonline to get notified on new song posts
DONATE to KeyLess Online
September 20, 2018support by contributing to the efforts of KeyLessOnline.com
Interested in learning keyboard?
October 17, 2018Message me from KeyLessOnline facebook page
Carnatic Notes for Varaveena Mrudu Paani (Carnatic Beginner Lesson  Geetham)
Language : Sanskrit
Song
:
Varaveena Mrudu Paani
Album
: Carnatic
Primer  GeethamComposer : Appayya DeekshitharRaagam   : Mohanam, See Legend for more details)            Aro: s r2 g3 p d2 S           Ava: S d2 p g3 r2 s
ThaaLam  : Roopakam (3 beats)
g  g  p    p

d  p  S    S
va ra vee...na..     mrudu
paa   ni
R  S  d  d  p

d  p  g  g  r
va na ru ha lO..     chana
ra....ni..
g  p  d  S  d

d  p  g  g  r
su ru chira bum.     bhara
ve.ni.....
g  g  d  p  g

p  g  g  r  s
su ra nu dhakal.
ya..........ni..
g  g  g  g  r
g
p  g  p    p
ni ru pa ma shubha   gu na lO....la..
g  g  d  p  d

d  p  S    S
ni ra thija ya..     prada
shee..la..
d  G  R  R  S
S
d  S  d  d  d  p
va ra da....priya    ranga na....ya.ki
g  p  d  S  d
p
d  p  g  g  r  s
va.an.chita pa la    da..........ya.ki
s  g  g    g

g  r  p  g  r
sa ra se....ja..     sa na ja na
ni..
s  r  s  g  r  s
ja ya ja ya ja ya (varaveenamrudupani)
About Us | Contact Us |
This work is licensed under a Creative Commons AttributionNonCommercialShareAlike 2.5 License.

In [ ]:
for i in range(0,len(lines)):
  print(lines[i])

Varaveena Geetham Mohanam Carnatic Carnatic Notes
KeyLess Online
Home
Song Notes
Tamil
Hindi
Telugu
Kannada
Malayalam
Kids Corner
Carnatic
Misc
Devotional
English
Punjabi
Marathi
Western Theory
RequestASong
Legend
FAQ
External Links
Pallavi Music Group
Sankara Eye Foundation
Sankara Nethralaya
Enter your search terms
Submit search form
News
KeyLess Online Facebook Page
September 26, 2016Like the facebook page to get notified on new song posts
KeyLess Online Twitter Feed
November 2, 2016Follow twitter handle @keylessonline to get notified on new song posts
DONATE to KeyLess Online
September 20, 2018support by contributing to the efforts of KeyLessOnline.com
Interested in learning keyboard?
October 17, 2018Message me from KeyLessOnline facebook page
Carnatic Notes for Varaveena Mrudu Paani (Carnatic Beginner Lesson  Geetham)
Language : Sanskrit
Song
:
Varaveena Mrudu Paani
Album
: Carnatic
Primer  GeethamComposer : Appayya DeekshitharRaagam   : Mohanam, See Legend for more details)            Aro: s r2 g3 p d2 S           Ava: S d2 p g3 r2 s
ThaaLam  : Roopakam (3 beats)
g  g  p    p

d  p  S    S
va ra vee...na..     mrudu
paa   ni
R  S  d  d  p

d  p  g  g  r
va na ru ha lO..     chana
ra....ni..
g  p  d  S  d

d  p  g  g  r
su ru chira bum.     bhara
ve.ni.....
g  g  d  p  g

p  g  g  r  s
su ra nu dhakal.
ya..........ni..
g  g  g  g  r
g
p  g  p    p
ni ru pa ma shubha   gu na lO....la..
g  g  d  p  d

d  p  S    S
ni ra thija ya..     prada
shee..la..
d  G  R  R  S
S
d  S  d  d  d  p
va ra da....priya    ranga na....ya.ki
g  p  d  S  d
p
d  p  g  g  r  s
va.an.chita pa la    da..........ya.ki
s  g  g    g

g  r  p  g  r
sa ra se....ja..     sa na ja na
ni..
s  r  s  g  r  s
ja ya ja ya ja ya (varaveenamrudupani)
About Us | Contact Us |
This work is licensed under a Creative Commons AttributionNonCommercialShareAlike 2.5 License.

In [ ]:

# Define the destination list
swara = []

# Define the starting index
starting_index = 44

# Loop through the source list and add the elements to the destination list
for i in range(starting_index, len(lines), 2):
    swara.append(lines[i])
    if i+2 < len(lines):
      swara.append(lines[i+1])

# Print the destination list
print(swara)

['g  g  p    p', '', 'd  p  S    S', 'va ra vee...na..     mrudu', 'paa   ni', 'R  S  d  d  p', '', 'd  p  g  g  r', 'va na ru ha lO..     chana', 'ra....ni..', 'g  p  d  S  d', '', 'd  p  g  g  r', 'su ru chira bum.     bhara', 've.ni.....', 'g  g  d  p  g', '', 'p  g  g  r  s', 'su ra nu dhakal.', 'ya..........ni..', 'g  g  g  g  r', 'g', 'p  g  p    p', 'ni ru pa ma shubha   gu na lO....la..', 'g  g  d  p  d', '', 'd  p  S    S', 'ni ra thija ya..     prada', 'shee..la..', 'd  G  R  R  S', 'S', 'd  S  d  d  d  p', 'va ra da....priya    ranga na....ya.ki', 'g  p  d  S  d', 'p', 'd  p  g  g  r  s', 'va.an.chita pa la    da..........ya.ki', 's  g  g    g', '', 'g  r  p  g  r', 'sa ra se....ja..     sa na ja na', 'ni..', 's  r  s  g  r  s', 'ja ya ja ya ja ya (varaveenamrudupani)', 'About Us | Contact Us |']

In [ ]:
for i in range(0,len(swara)):
  print(swara[i])

g  g  p    p

d  p  S    S
va ra vee...na..     mrudu
paa   ni
R  S  d  d  p

d  p  g  g  r
va na ru ha lO..     chana
ra....ni..
g  p  d  S  d

d  p  g  g  r
su ru chira bum.     bhara
ve.ni.....
g  g  d  p  g

p  g  g  r  s
su ra nu dhakal.
ya..........ni..
g  g  g  g  r
g
p  g  p    p
ni ru pa ma shubha   gu na lO....la..
g  g  d  p  d

d  p  S    S
ni ra thija ya..     prada
shee..la..
d  G  R  R  S
S
d  S  d  d  d  p
va ra da....priya    ranga na....ya.ki
g  p  d  S  d
p
d  p  g  g  r  s
va.an.chita pa la    da..........ya.ki
s  g  g    g

g  r  p  g  r
sa ra se....ja..     sa na ja na
ni..
s  r  s  g  r  s
ja ya ja ya ja ya (varaveenamrudupani)
About Us | Contact Us |

In [ ]:
def remove_dots_and_empty(lst):
    return [x for x in lst if (not '.' in x) and (x != '')]

In [ ]:
new_list = remove_dots_and_empty(swara)
print(new_list)  # Output: ['abc', 'pqr', 'stu']

['g  g  p    p', 'd  p  S    S', 'paa   ni', 'R  S  d  d  p', 'd  p  g  g  r', 'g  p  d  S  d', 'd  p  g  g  r', 'g  g  d  p  g', 'p  g  g  r  s', 'g  g  g  g  r', 'g', 'p  g  p    p', 'g  g  d  p  d', 'd  p  S    S', 'd  G  R  R  S', 'S', 'd  S  d  d  d  p', 'g  p  d  S  d', 'p', 'd  p  g  g  r  s', 's  g  g    g', 'g  r  p  g  r', 's  r  s  g  r  s', 'ja ya ja ya ja ya (varaveenamrudupani)', 'About Us | Contact Us |']

In [ ]:
import pandas as pd
df = pd.DataFrame(new_list, columns = ['Notes'])
df.head()

           Notes
0   g  g  p    p
1   d  p  S    S
2       paa   ni
3  R  S  d  d  p
4  d  p  g  g  r

Doing this for another song

In [ ]:
import requests
from bs4 import BeautifulSoup

# Send a GET request to the URL
url = 'https://spirit4lyf.wordpress.com/mohana-ragam-ninnu-kori/'
response = requests.get(url)

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Extract all the text from the webpage and split it by newline characters
text = soup.get_text()
lines = text.split('\n')

# Remove any empty lines from the list and replace non-breaking space characters and hyphens
lines = [line.replace('\xa0', ' ').replace('-', '').strip() for line in lines if line.strip()]

# Print each line on a new line
for line in lines:
    print(line)

MOHANA RAGAM (Ninnu kori) | spirit4lyf
spirit4lyf
improve essence of life
Menu
Skip to content
Home
Artattack
Noting but food
Music
SARALISWARULU
JANTASWARULU
ALANKARALU
GEETALU
SWARAJATHULU
SWARAPALLAVULU
VARNALU Lyrics
keerthanalu
Projects
Tableau Project
Search for:
MOHANA RAGAM (Ninnu kori)
mohanaRAGAM : Mohana TAALAM : Aadi Rachana : Sannuthanga Sreenivasa
MOORCHANA : Assending — sa ri ga pa da sa .
Decending — sa da pa ga ri sa
Pallavi:
G    ,    G    ,            R    ,    ,    ,            S    S    R    R          G    G    R    R |
Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –
S    R    G    R          S    R     S    D   |    S    R    G    P          G     R    S    R ||
Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –
G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R |
Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –
G    P   G  P           D    P    D   S   |    D   .    P  G          D    P    G    R  ||
lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –
Anupallavi:
G    ,    G    ,             P    ,    ,    ,            G    G    P    P          D    D    P    ,   |
Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –
D    S    D    D          P   G   D    P     |   D  G    D    P          G    R    S    R               ||
Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –
G    G    P    P           D    P   D   S        D    S    R    S           G    R     ,    S               |
Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa
D    S    R    S           ,   D   P    D      |    S    D    ,    P               G    R    S    R             ||
–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –
Mukthayi Swaram:
G    ,    R    G              R    S    R    ,            S    R    S    G          R    G    S    R            |
S    D    S    R              G    R    G   P   |        G    P    D    ,            P     ,      ,     ,          ||
G    P    D    P             D    S    R   G       R   ,    G   S        ,    R    D    ,    |
S   P    ,    D              S    R    G   S     |       ,    D    P     ,             G     R      S     R ||
Charanam:
G    ,    G    ,      G   ;      R    G     P    G    P    –   P    ,    ,    ,              |
San –   nu   –  tham     ga  – –    –      Sree –    –     –    –
G    G    D   D                P     ,    G    G   |     D    P   G   P          G    R    S    R   ||
ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –
Chittai Swaras:
(1) G    ,    ,    ,                    R    ,    S    ,              R    ,    ,    ,                D    ,    ,    ,              |
R    ,    D    ,                   S    ,    ,    ,           |     R    ,    ,    ,                G    ,    R    , || (san)
(2) G    ,    G    R                G    R    S    R          G    ,    G    P           D    D    S    R  |
G    ,    G    G                D    P    G    R     |     G    ,    G    S          D    P    G    R  || (San)
(3) P    ,    D    D                    P    ,    G    R               S    ,    R    G          R    ,    S    D  |
S    ,    R    G                    P    ,    D    ,        |         S    S  ,     D         P    ,    G    R  || (San)
(4) S    ,    R    G              R    S    R    S           D    S    D    P         G    R    S    R    |
S     ,    ; ;     S    S       |        R    R    G    G         P    P    D    D  ||
S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        |
S  D  G    P                 D  P    D   P      |         R    S    D    P         G    R    S    R  || (San)
Share this:PrintWhatsAppFacebookEmailTwitterLinkedInSkypePinterestRedditLike this:Like Loading...
looking for something?
Search for:
Blog Stats
386,721 hits
April 2023
S
M
T
W
T
F
S
1
2345678
9101112131415
16171819202122
23242526272829
30
« Jul
Follow spirit4lyf on WordPress.com
Recent Posts
Tableau Project
APPE GULABJAMUN
SWEET DUMPLINGS(JILLEDIKAYALU)
QUINOA TEHRI
RAJMA CUTLET
Recent Comments
choti on Ganesh chaturdhi clay art…Saroja on Bread guntaponganaluVARNALU – spir… on Darbar ragam varnam (chal…GEETALU – spir… on SARALISWARULUKeerthi reddy on HEALTHY WRAP
Create a free website or blog at WordPress.com.
Privacy & Cookies: This site uses cookies. By continuing to use this website, you agree to their use.
To find out more, including how to control cookies, see here:
Cookie Policy
Follow
Following
spirit4lyf
Sign me up
Already have a WordPress.com account? Log in now.
spirit4lyf
Customize
Follow
Following
Sign up
Log in
Copy shortlink
Report this content
View post in Reader
Manage subscriptions
Collapse this bar
%d bloggers like this:

In [ ]:
for i in range(0,len(lines)):
  print(lines[i])

MOHANA RAGAM (Ninnu kori) | spirit4lyf
spirit4lyf
improve essence of life
Menu
Skip to content
Home
Artattack
Noting but food
Music
SARALISWARULU
JANTASWARULU
ALANKARALU
GEETALU
SWARAJATHULU
SWARAPALLAVULU
VARNALU Lyrics
keerthanalu
Projects
Tableau Project
Search for:
MOHANA RAGAM (Ninnu kori)
mohanaRAGAM : Mohana TAALAM : Aadi Rachana : Sannuthanga Sreenivasa
MOORCHANA : Assending — sa ri ga pa da sa .
Decending — sa da pa ga ri sa
Pallavi:
G    ,    G    ,            R    ,    ,    ,            S    S    R    R          G    G    R    R |
Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –
S    R    G    R          S    R     S    D   |    S    R    G    P          G     R    S    R ||
Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –
G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R |
Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –
G    P   G  P           D    P    D   S   |    D   .    P  G          D    P    G    R  ||
lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –
Anupallavi:
G    ,    G    ,             P    ,    ,    ,            G    G    P    P          D    D    P    ,   |
Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –
D    S    D    D          P   G   D    P     |   D  G    D    P          G    R    S    R               ||
Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –
G    G    P    P           D    P   D   S        D    S    R    S           G    R     ,    S               |
Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa
D    S    R    S           ,   D   P    D      |    S    D    ,    P               G    R    S    R             ||
–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –
Mukthayi Swaram:
G    ,    R    G              R    S    R    ,            S    R    S    G          R    G    S    R            |
S    D    S    R              G    R    G   P   |        G    P    D    ,            P     ,      ,     ,          ||
G    P    D    P             D    S    R   G       R   ,    G   S        ,    R    D    ,    |
S   P    ,    D              S    R    G   S     |       ,    D    P     ,             G     R      S     R ||
Charanam:
G    ,    G    ,      G   ;      R    G     P    G    P    –   P    ,    ,    ,              |
San –   nu   –  tham     ga  – –    –      Sree –    –     –    –
G    G    D   D                P     ,    G    G   |     D    P   G   P          G    R    S    R   ||
ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –
Chittai Swaras:
(1) G    ,    ,    ,                    R    ,    S    ,              R    ,    ,    ,                D    ,    ,    ,              |
R    ,    D    ,                   S    ,    ,    ,           |     R    ,    ,    ,                G    ,    R    , || (san)
(2) G    ,    G    R                G    R    S    R          G    ,    G    P           D    D    S    R  |
G    ,    G    G                D    P    G    R     |     G    ,    G    S          D    P    G    R  || (San)
(3) P    ,    D    D                    P    ,    G    R               S    ,    R    G          R    ,    S    D  |
S    ,    R    G                    P    ,    D    ,        |         S    S  ,     D         P    ,    G    R  || (San)
(4) S    ,    R    G              R    S    R    S           D    S    D    P         G    R    S    R    |
S     ,    ; ;     S    S       |        R    R    G    G         P    P    D    D  ||
S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        |
S  D  G    P                 D  P    D   P      |         R    S    D    P         G    R    S    R  || (San)
Share this:PrintWhatsAppFacebookEmailTwitterLinkedInSkypePinterestRedditLike this:Like Loading...
looking for something?
Search for:
Blog Stats
386,721 hits
April 2023
S
M
T
W
T
F
S
1
2345678
9101112131415
16171819202122
23242526272829
30
« Jul
Follow spirit4lyf on WordPress.com
Recent Posts
Tableau Project
APPE GULABJAMUN
SWEET DUMPLINGS(JILLEDIKAYALU)
QUINOA TEHRI
RAJMA CUTLET
Recent Comments
choti on Ganesh chaturdhi clay art…Saroja on Bread guntaponganaluVARNALU – spir… on Darbar ragam varnam (chal…GEETALU – spir… on SARALISWARULUKeerthi reddy on HEALTHY WRAP
Create a free website or blog at WordPress.com.
Privacy & Cookies: This site uses cookies. By continuing to use this website, you agree to their use.
To find out more, including how to control cookies, see here:
Cookie Policy
Follow
Following
spirit4lyf
Sign me up
Already have a WordPress.com account? Log in now.
spirit4lyf
Customize
Follow
Following
Sign up
Log in
Copy shortlink
Report this content
View post in Reader
Manage subscriptions
Collapse this bar
%d bloggers like this:

In [ ]:
lines[62]

'S  D  G    P                 D  P    D   P      |         R    S    D    P         G    R    S    R  || (San)'

In [ ]:
#25-62

varnam = []

for i in range(25, 62):
  varnam.append(lines[i])

In [ ]:
varnam

['G    ,    G    ,            R    ,    ,    ,            S    S    R    R          G    G    R    R |',
 'Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –',
 'S    R    G    R          S    R     S    D   |    S    R    G    P          G     R    S    R ||',
 'Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –',
 'G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R |',
 'Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –',
 'G    P   G  P           D    P    D   S   |    D   .    P  G          D    P    G    R  ||',
 'lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –',
 'Anupallavi:',
 'G    ,    G    ,             P    ,    ,    ,            G    G    P    P          D    D    P    ,   |',
 'Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –',
 'D    S    D    D          P   G   D    P     |   D  G    D    P          G    R    S    R               ||',
 'Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –',
 'G    G    P    P           D    P   D   S        D    S    R    S           G    R     ,    S               |',
 'Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa',
 'D    S    R    S           ,   D   P    D      |    S    D    ,    P               G    R    S    R             ||',
 '–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –',
 'Mukthayi Swaram:',
 'G    ,    R    G              R    S    R    ,            S    R    S    G          R    G    S    R            |',
 'S    D    S    R              G    R    G   P   |        G    P    D    ,            P     ,      ,     ,          ||',
 'G    P    D    P             D    S    R   G       R   ,    G   S        ,    R    D    ,    |',
 'S   P    ,    D              S    R    G   S     |       ,    D    P     ,             G     R      S     R ||',
 'Charanam:',
 'G    ,    G    ,      G   ;      R    G     P    G    P    –   P    ,    ,    ,              |',
 'San –   nu   –  tham     ga  – –    –      Sree –    –     –    –',
 'G    G    D   D                P     ,    G    G   |     D    P   G   P          G    R    S    R   ||',
 'ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –',
 'Chittai Swaras:',
 '(1) G    ,    ,    ,                    R    ,    S    ,              R    ,    ,    ,                D    ,    ,    ,              |',
 'R    ,    D    ,                   S    ,    ,    ,           |     R    ,    ,    ,                G    ,    R    , || (san)',
 '(2) G    ,    G    R                G    R    S    R          G    ,    G    P           D    D    S    R  |',
 'G    ,    G    G                D    P    G    R     |     G    ,    G    S          D    P    G    R  || (San)',
 '(3) P    ,    D    D                    P    ,    G    R               S    ,    R    G          R    ,    S    D  |',
 'S    ,    R    G                    P    ,    D    ,        |         S    S  ,     D         P    ,    G    R  || (San)',
 '(4) S    ,    R    G              R    S    R    S           D    S    D    P         G    R    S    R    |',
 'S     ,    ; ;     S    S       |        R    R    G    G         P    P    D    D  ||',
 'S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        |']

In [ ]:
area = ["Anupallavi:","Mukthayi Swaram:","Charanam:","Chittai Swaras:"]


if "Chittai Swaras:" in varnam:
    varnam.remove("Chittai Swaras:")

print(varnam)

['G    ,    G    ,            R    ,    ,    ,            S    S    R    R          G    G    R    R |', 'Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –', 'S    R    G    R          S    R     S    D   |    S    R    G    P          G     R    S    R ||', 'Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –', 'G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R |', 'Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –', 'G    P   G  P           D    P    D   S   |    D   .    P  G          D    P    G    R  ||', 'lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –', 'Anupallavi:', 'G    ,    G    ,             P    ,    ,    ,            G    G    P    P          D    D    P    ,   |', 'Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –', 'D    S    D    D          P   G   D    P     |   D  G    D    P          G    R    S    R               ||', 'Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –', 'G    G    P    P           D    P   D   S        D    S    R    S           G    R     ,    S               |', 'Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa', 'D    S    R    S           ,   D   P    D      |    S    D    ,    P               G    R    S    R             ||', '–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –', 'Mukthayi Swaram:', 'G    ,    R    G              R    S    R    ,            S    R    S    G          R    G    S    R            |', 'S    D    S    R              G    R    G   P   |        G    P    D    ,            P     ,      ,     ,          ||', 'G    P    D    P             D    S    R   G       R   ,    G   S        ,    R    D    ,    |', 'S   P    ,    D              S    R    G   S     |       ,    D    P     ,             G     R      S     R ||', 'Charanam:', 'G    ,    G    ,      G   ;      R    G     P    G    P    –   P    ,    ,    ,              |', 'San –   nu   –  tham     ga  – –    –      Sree –    –     –    –', 'G    G    D   D                P     ,    G    G   |     D    P   G   P          G    R    S    R   ||', 'ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –', '(1) G    ,    ,    ,                    R    ,    S    ,              R    ,    ,    ,                D    ,    ,    ,              |', 'R    ,    D    ,                   S    ,    ,    ,           |     R    ,    ,    ,                G    ,    R    , || (san)', '(2) G    ,    G    R                G    R    S    R          G    ,    G    P           D    D    S    R  |', 'G    ,    G    G                D    P    G    R     |     G    ,    G    S          D    P    G    R  || (San)', '(3) P    ,    D    D                    P    ,    G    R               S    ,    R    G          R    ,    S    D  |', 'S    ,    R    G                    P    ,    D    ,        |         S    S  ,     D         P    ,    G    R  || (San)', '(4) S    ,    R    G              R    S    R    S           D    S    D    P         G    R    S    R    |', 'S     ,    ; ;     S    S       |        R    R    G    G         P    P    D    D  ||', 'S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        |']

In [ ]:
for i in range(0, len(varnam)):
  print(varnam[i])

G    ,    G    ,            R    ,    ,    ,            S    S    R    R          G    G    R    R |
Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –
S    R    G    R          S    R     S    D   |    S    R    G    P          G     R    S    R ||
Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –
G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R |
Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –
G    P   G  P           D    P    D   S   |    D   .    P  G          D    P    G    R  ||
lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –
Anupallavi:
G    ,    G    ,             P    ,    ,    ,            G    G    P    P          D    D    P    ,   |
Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –
D    S    D    D          P   G   D    P     |   D  G    D    P          G    R    S    R               ||
Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –
G    G    P    P           D    P   D   S        D    S    R    S           G    R     ,    S               |
Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa
D    S    R    S           ,   D   P    D      |    S    D    ,    P               G    R    S    R             ||
–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –
Mukthayi Swaram:
G    ,    R    G              R    S    R    ,            S    R    S    G          R    G    S    R            |
S    D    S    R              G    R    G   P   |        G    P    D    ,            P     ,      ,     ,          ||
G    P    D    P             D    S    R   G       R   ,    G   S        ,    R    D    ,    |
S   P    ,    D              S    R    G   S     |       ,    D    P     ,             G     R      S     R ||
Charanam:
G    ,    G    ,      G   ;      R    G     P    G    P    –   P    ,    ,    ,              |
San –   nu   –  tham     ga  – –    –      Sree –    –     –    –
G    G    D   D                P     ,    G    G   |     D    P   G   P          G    R    S    R   ||
ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –
(1) G    ,    ,    ,                    R    ,    S    ,              R    ,    ,    ,                D    ,    ,    ,              |
R    ,    D    ,                   S    ,    ,    ,           |     R    ,    ,    ,                G    ,    R    , || (san)
(2) G    ,    G    R                G    R    S    R          G    ,    G    P           D    D    S    R  |
G    ,    G    G                D    P    G    R     |     G    ,    G    S          D    P    G    R  || (San)
(3) P    ,    D    D                    P    ,    G    R               S    ,    R    G          R    ,    S    D  |
S    ,    R    G                    P    ,    D    ,        |         S    S  ,     D         P    ,    G    R  || (San)
(4) S    ,    R    G              R    S    R    S           D    S    D    P         G    R    S    R    |
S     ,    ; ;     S    S       |        R    R    G    G         P    P    D    D  ||
S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        |

In [ ]:
import re



# Define regular expressions to match the patterns you want to remove
regex1 = r'[\||\|\||,\;\()]'  # Matches | or || or ,
regex2 = r'\(\d+\)'  # Matches parentheses with numbers, e.g. (1), (2)
regex3 = r'\b[sS][aA][nN]\d+\b'  # Matches the word (san)

# Remove the patterns from each string in the dataset
hehe = []
for d in varnam:
    # Replace the matched patterns with an empty string
    d = re.sub(regex1, '', d)
    d = re.sub(regex2, '', d)
    d = re.sub(regex3, '', d)
    hehe.append(d)

# Print the cleaned dataset
print(hehe)

['G        G                R                        S    S    R    R          G    G    R    R ', 'Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –', 'S    R    G    R          S    R     S    D       S    R    G    P          G     R    S    R ', 'Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –', 'G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R ', 'Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –', 'G    P   G  P           D    P    D   S       D   .    P  G          D    P    G    R  ', 'lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –', 'Anupallavi:', 'G        G                 P                        G    G    P    P          D    D    P       ', 'Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –', 'D    S    D    D          P   G   D    P        D  G    D    P          G    R    S    R               ', 'Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –', 'G    G    P    P           D    P   D   S        D    S    R    S           G    R         S               ', 'Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa', 'D    S    R    S              D   P    D          S    D        P               G    R    S    R             ', '–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –', 'Mukthayi Swaram:', 'G        R    G              R    S    R                S    R    S    G          R    G    S    R            ', 'S    D    S    R              G    R    G   P           G    P    D                P                          ', 'G    P    D    P             D    S    R   G       R       G   S            R    D        ', 'S   P        D              S    R    G   S                D    P                  G     R      S     R ', 'Charanam:', 'G        G          G         R    G     P    G    P    –   P                          ', 'San –   nu   –  tham     ga  – –    –      Sree –    –     –    –', 'G    G    D   D                P         G    G        D    P   G   P          G    R    S    R   ', 'ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –', '1 G                                R        S                  R                            D                          ', 'R        D                       S                            R                            G        R      san', '2 G        G    R                G    R    S    R          G        G    P           D    D    S    R  ', 'G        G    G                D    P    G    R          G        G    S          D    P    G    R   San', '3 P        D    D                    P        G    R               S        R    G          R        S    D  ', 'S        R    G                    P        D                     S    S       D         P        G    R   San', '4 S        R    G              R    S    R    S           D    S    D    P         G    R    S    R    ', 'S               S    S               R    R    G    G         P    P    D    D  ', 'S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        ']

In [ ]:
hehe

['G        G                R                        S    S    R    R          G    G    R    R ',
 'Nin –   nu   –            ko  –   –   –             ri    –    –    –               –     –    –     –',
 'S    R    G    R          S    R     S    D       S    R    G    P          G     R    S    R ',
 'Yu  –    –     –           nna –     –    –          nu   –     –    –            ra     –    –     –',
 'G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R ',
 'Ni   –   –    –               –    –  ki   –         –    –    –    –        la    –     –    –',
 'G    P   G  P           D    P    D   S       D   .    P  G          D    P    G    R  ',
 'lo    –   –  ka            –     –  na   –      –    –    – ya           –     –    ka   –',
 'Anupallavi:',
 'G        G                 P                        G    G    P    P          D    D    P       ',
 'Nan –   nu   –         pa   –   –   –          li    –    –    –          –    im   pa     –',
 'D    S    D    D          P   G   D    P        D  G    D    P          G    R    S    R               ',
 'Sa   –    ma   –       –    –  ya    –          –    mu   –    –       ra   –   –    –',
 'G    G    P    P           D    P   D   S        D    S    R    S           G    R         S               ',
 'Na  –    –     –          –    –   mee   –   –   da     –    –            kru  –     –   pa',
 'D    S    R    S              D   P    D          S    D        P               G    R    S    R             ',
 '–     –     –    ju     –       –   –   da           –    ra   –     –               –   –    –    –',
 'Mukthayi Swaram:',
 'G        R    G              R    S    R                S    R    S    G          R    G    S    R            ',
 'S    D    S    R              G    R    G   P           G    P    D                P                          ',
 'G    P    D    P             D    S    R   G       R       G   S            R    D        ',
 'S   P        D              S    R    G   S                D    P                  G     R      S     R ',
 'Charanam:',
 'G        G          G         R    G     P    G    P    –   P                          ',
 'San –   nu   –  tham     ga  – –    –      Sree –    –     –    –',
 'G    G    D   D                P         G    G        D    P   G   P          G    R    S    R   ',
 'ni   –   –    –                  –    –      va    –         –    –      sa   –            –    –     –    –',
 '1 G                                R        S                  R                            D                          ',
 'R        D                       S                            R                            G        R      san',
 '2 G        G    R                G    R    S    R          G        G    P           D    D    S    R  ',
 'G        G    G                D    P    G    R          G        G    S          D    P    G    R   San',
 '3 P        D    D                    P        G    R               S        R    G          R        S    D  ',
 'S        R    G                    P        D                     S    S       D         P        G    R   San',
 '4 S        R    G              R    S    R    S           D    S    D    P         G    R    S    R    ',
 'S               S    S               R    R    G    G         P    P    D    D  ',
 'S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D        ']

In [ ]:
hehe = pd.DataFrame(hehe)
hehe.head()

                                                   0
0  G        G                R                   ...
1  Nin –   nu   –            ko  –   –   –       ...
2  S    R    G    R          S    R     S    D   ...
3  Yu  –    –     –           nna –     –    –   ...
4  G    P   G   G            R    S    R   G     ...

In [ ]:
from google.colab import files
hehe.to_csv('output2.csv', encoding = 'utf-8-sig') 
files.download('output2.csv')

## Generation of first form of dataset is complete. Here comes another one.

## Second Iteration

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/output2.csv')
df.head()

                                               Notes
0  G        G                R                   ...
1  S    R    G    R          S    R     S    D   ...
2  G    P   G   G            R    S    R   G     ...
3  G    P   G  P           D    P    D   S       ...
4  G        G                 P                  ...

In [ ]:
# convert every element of the dataframe to uppercase
df = df.applymap(lambda x: x.upper() if isinstance(x, str) else x)

print(df)

                                                Notes
0   G        G                R                   ...
1   S    R    G    R          S    R     S    D   ...
2   G    P   G   G            R    S    R   G     ...
3   G    P   G  P           D    P    D   S       ...
4   G        G                 P                  ...
5   D    S    D    D          P   G   D    P      ...
6   G    G    P    P           D    P   D   S     ...
7   D    S    R    S              D   P    D      ...
8   G        R    G              R    S    R      ...
9   S    D    S    R              G    R    G   P ...
10  G    P    D    P             D    S    R   G  ...
11  S   P        D              S    R    G   S   ...
12  G        G          G         R    G     P    ...
13  G    G    D   D                P         G    ...
14  G                                R        S   ...
15  R        D                       S            ...
16   G        G    R                G    R    S   ...
17  G        G    G                D    P    G    ...
18   P        D    D                    P        G...
19  S        R    G                    P        D ...
20   S        R    G              R    S    R    S...
21  S               S    S               R    R   ...
22  S   R   G   R               G    R  D  S      ...
23                                       G  G  P    P
24                                       D  P  S    S
25                                      R  S  D  D  P
26                                      D  P  G  G  R
27                                      G  P  D  S  D
28                                      D  P  G  G  R
29                                      G  G  D  P  G
30                                      P  G  G  R  S
31                                      G  G  G  G  R
32                                       P  G  P    P
33                                      G  G  D  P  D
34                                       D  P  S    S
35                                      D  G  R  R  S
36                                   D  S  D  D  D  P
37                                      G  P  D  S  D
38                                   D  P  G  G  R  S
39                                       S  G  G    G
40                                      G  R  P  G  R
41                                   S  R  S  G  R  S

In [ ]:
import numpy as np

df['Notes'] = df['Notes'].tolist()

In [ ]:
for i in range(0,len(df['Notes'])):
  print(df['Notes'][i])

G        G                R                        S    S    R    R          G    G    R    R
S    R    G    R          S    R     S    D       S    R    G    P          G     R    S    R
G    P   G   G            R    S    R   G       R    R    S    D          S    R     G    R
G    P   G  P           D    P    D   S       D    P  G          D    P    G    R
G        G                 P                        G    G    P    P          D    D    P
D    S    D    D          P   G   D    P        D  G    D    P          G    R    S    R
G    G    P    P           D    P   D   S        D    S    R    S           G    R         S
D    S    R    S              D   P    D          S    D        P               G    R    S    R
G        R    G              R    S    R                S    R    S    G          R    G    S    R
S    D    S    R              G    R    G   P           G    P    D                P
G    P    D    P             D    S    R   G       R       G   S            R    D
S   P        D              S    R    G   S                D    P                  G     R      S     R
G        G          G         R    G     P    G    P    P
G    G    D   D                P         G    G        D    P   G   P          G    R    S    R
G                                R        S                  R                            D
R        D                       S                            R                            G        R
 G        G    R                G    R    S    R          G        G    P           D    D    S    R
G        G    G                D    P    G    R          G        G    S          D    P    G    R
 P        D    D                    P        G    R               S        R    G          R        S    D
S        R    G                    P        D                     S    S       D         P        G    R
 S        R    G              R    S    R    S           D    S    D    P         G    R    S    R
S               S    S               R    R    G    G         P    P    D    D
S   R   G   R               G    R  D  S           R  S    R    S      P    D    S    D
G  G  P    P
D  P  S    S
R  S  D  D  P
D  P  G  G  R
G  P  D  S  D
D  P  G  G  R
G  G  D  P  G
P  G  G  R  S
G  G  G  G  R
P  G  P    P
G  G  D  P  D
D  P  S    S
D  G  R  R  S
D  S  D  D  D  P
G  P  D  S  D
D  P  G  G  R  S
S  G  G    G
G  R  P  G  R
S  R  S  G  R  S

In [ ]:
# shuffle the rows of the dataframe randomly
df = df.sample(frac=1)
df = df.sample(frac = 1).reset_index(drop = True)

In [ ]:
df

                                                Notes
0   D    S    R    S              D   P    D      ...
1   S    R    G    R          S    R     S    D   ...
2    G        G    R                G    R    S   ...
3   S   P        D              S    R    G   S   ...
4                                        S  G  G    G
5                                       G  P  D  S  D
6                                       P  G  G  R  S
7   G        R    G              R    S    R      ...
8                                        P  G  P    P
9    S        R    G              R    S    R    S...
10  G        G          G         R    G     P    ...
11                                      D  P  G  G  R
12  G                                R        S   ...
13                                   D  S  D  D  D  P
14                                   D  P  G  G  R  S
15                                      G  P  D  S  D
16                                      D  G  R  R  S
17  G        G                 P                  ...
18                                       D  P  S    S
19   P        D    D                    P        G...
20  D    S    D    D          P   G   D    P      ...
21                                      R  S  D  D  P
22                                      G  G  D  P  D
23  G        G    G                D    P    G    ...
24  S        R    G                    P        D ...
25  G        G                R                   ...
26                                      D  P  G  G  R
27  S               S    S               R    R   ...
28                                   S  R  S  G  R  S
29  G    G    D   D                P         G    ...
30  S   R   G   R               G    R  D  S      ...
31  G    P   G   G            R    S    R   G     ...
32  G    G    P    P           D    P   D   S     ...
33                                      G  R  P  G  R
34  G    P    D    P             D    S    R   G  ...
35                                      G  G  D  P  G
36                                      G  G  G  G  R
37  G    P   G  P           D    P    D   S       ...
38                                       G  G  P    P
39  R        D                       S            ...
40                                       D  P  S    S
41  S    D    S    R              G    R    G   P ...

In [ ]:
df = pd.concat([df] * 7, ignore_index=True)

print(df)

                                                 Notes
0    D    S    R    S              D   P    D      ...
1    S    R    G    R          S    R     S    D   ...
2     G        G    R                G    R    S   ...
3    S   P        D              S    R    G   S   ...
4                                         S  G  G    G
..                                                 ...
289  G    P   G  P           D    P    D   S       ...
290                                       G  G  P    P
291  R        D                       S            ...
292                                       D  P  S    S
293  S    D    S    R              G    R    G   P ...

[294 rows x 1 columns]

In [ ]:
# shuffle the rows of the dataframe randomly
df = df.sample(frac=1)
df = df.sample(frac = 1).reset_index(drop = True)

In [ ]:
df.head()

                                               Notes
0                                       D  P  S    S
1  G        R    G              R    S    R      ...
2                                       S  G  G    G
3                                      G  G  D  P  D
4  G                                R        S   ...

In [ ]:
# shuffle the values within each row
for i in range(len(df)):
  if(i%3 == 0):
    np.random.shuffle(df.iloc[i].values)

print(df)

                                                 Notes
0                                         D  P  S    S
1    G        R    G              R    S    R      ...
2                                         S  G  G    G
3                                        G  G  D  P  D
4    G                                R        S   ...
..                                                 ...
289                                      P  G  G  R  S
290                                   S  R  S  G  R  S
291  S   P        D              S    R    G   S   ...
292  G        G          G         R    G     P    ...
293  G    G    P    P           D    P   D   S     ...

[294 rows x 1 columns]

In [ ]:
# shuffle the values within each row
for i in range(len(df)):
  if(i%7 == 0):
    np.random.shuffle(df.iloc[i].values)

print(df)

                                                 Notes
0                                         D  P  S    S
1    G        R    G              R    S    R      ...
2                                         S  G  G    G
3                                        G  G  D  P  D
4    G                                R        S   ...
..                                                 ...
289                                      P  G  G  R  S
290                                   S  R  S  G  R  S
291  S   P        D              S    R    G   S   ...
292  G        G          G         R    G     P    ...
293  G    G    P    P           D    P   D   S     ...

[294 rows x 1 columns]

In [ ]:
# apply string operations to all rows
df = df.apply(lambda x: x.str.replace('\s+', ' ').str.strip())

print(df)

                             Notes
0                          D P S S
1      G R G R S R S R S G R G S R
2                          S G G G
3                        G G D P D
4                        G R S R D
..                             ...
289                      P G G R S
290                    S R S G R S
291      S P D S R G S D P G R S R
292              G G G R G P G P P
293  G G P P D P D S D S R S G R S

[294 rows x 1 columns]

<ipython-input-115-24f7ca024016>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df = df.apply(lambda x: x.str.replace('\s+', ' ').str.strip())

In [ ]:
from google.colab import files
df.to_csv('df.csv', encoding = 'utf-8-sig') 
files.download('df.csv')

## Generation of second form of dataset is complete.

Here we cleaned the dataset, shuffled it, volumnized it so as to encourage a better model accuracy.

## Third Iteration

In [ ]:
notes = pd.read_csv('/content/notes.csv')
notes.head()

                         Notes
0                      D P S S
1  G R G R S R S R S G R G S R
2                      S G G G
3                    G G D P D
4                    G R S R D

### Mapping

In [ ]:
type(df['Notes'][1])

str

### Here I map notes to their respective frequencies found in the piano, and so these numbers were attained.

In [ ]:
import pandas as pd
import numpy as np
from statistics import mean

# define the mappings
mapping_dict = {'D': [110, 220],
                'S': [130.81, 261.63],
                'R': [146.83, 293.66],
                'G': [164.81, 329.63],
                'P': [196]}

In [ ]:
# read in the dataframe
df = pd.read_csv('/content/notes.csv', header=0, delimiter = '\t')

In [ ]:
df.head()

                         Notes
0                      D P S S
1  G R G R S R S R S G R G S R
2                      S G G G
3                    G G D P D
4                    G R S R D

In [ ]:
type(df['Notes'][1])

str

In [ ]:
df2 = df.copy()
df2.head()

                         Notes
0                      D P S S
1  G R G R S R S R S G R G S R
2                      S G G G
3                    G G D P D
4                    G R S R D

In [ ]:
import pandas as pd



# define function to convert each row to a list
def row_to_list(row):
    return row.split()

# apply function to each row
df2['Notes'] = df2['Notes'].apply(row_to_list)

In [ ]:
df2.head()

                                        Notes
0                                [D, P, S, S]
1  [G, R, G, R, S, R, S, R, S, G, R, G, S, R]
2                                [S, G, G, G]
3                             [G, G, D, P, D]
4                             [G, R, S, R, D]

In [ ]:
from google.colab import files
df2.to_csv('df2.csv', encoding = 'utf-8-sig') 
files.download('df2.csv')

I will use the above dataset for the pattern mining algorithm

In [ ]:
# apply pd.Series constructor to each element of the 'Notes' column to create new columns
new_df = df['Notes'].apply(pd.Series)

# rename the new columns
new_df = new_df.rename(columns=lambda x: f'Column_{x+1}')

print(new_df)

                          Column_1
0                          D P S S
1      G R G R S R S R S G R G S R
2                          S G G G
3                        G G D P D
4                        G R S R D
..                             ...
289                      P G G R S
290                    S R S G R S
291      S P D S R G S D P G R S R
292              G G G R G P G P P
293  G G P P D P D S D S R S G R S

[294 rows x 1 columns]

In [ ]:
new_df.head()

                      Column_1
0                      D P S S
1  G R G R S R S R S G R G S R
2                      S G G G
3                    G G D P D
4                    G R S R D

## Generation of third form is complete.

Here we did some more cleaning. However we removed the spaces and made it look more compact.

## Fourth Iteration

Here i plan to split the above notes all in one line, to different columns across the dataset.

In [ ]:
# Create a new dataframe with empty columns
new_df = pd.DataFrame(columns=range(31))

# Iterate over each row in the original dataframe
for i, row in df.iterrows():
    # Get the list of notes in the row
    notes = row['Notes']
    # Iterate over each note in the list
    for j, note in enumerate(notes):
        # Set the value of the new dataframe at the ith row and jth column to the note
        new_df.at[i, j] = note

# Rename the columns of the new dataframe
new_df.columns = [f'Note_{i+1}' for i in range(31)]

# Concatenate the original dataframe and the new dataframe
result = pd.concat([df, new_df], axis=1)

In [ ]:
result

,Notes,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,...,Note_22,Note_23,Note_24,Note_25,Note_26,Note_27,Note_28,Note_29,Note_30,Note_31
0,D P S S,D,,P,,S,,S,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,G R G R S R S R S G R G S R,G,,R,,G,,R,,S,...,,G,,S,,R,NaN,NaN,NaN,NaN
2,S G G G,S,,G,,G,,G,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,G G D P D,G,,G,,D,,P,,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,G R S R D,G,,R,,S,,R,,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,P G G R S,P,,G,,G,,R,,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,S R S G R S,S,,R,,S,,G,,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,S P D S R G S D P G R S R,S,,P,,D,,S,,R,...,,S,,R,NaN,NaN,NaN,NaN,NaN,NaN
292,G G G R G P G P P,G,,G,,G,,R,,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,G G P P D P D S D S R S G R S,G,,G,,P,,P,,D,...,,S,,G,,R,,S,NaN,NaN

In [ ]:
# fill NaN values with any of the notes in the same row
result = result.apply(lambda row: row.fillna(np.random.choice(row.dropna())), axis=1)

print(result)

                             Notes Note_1 Note_2 Note_3 Note_4 Note_5 Note_6  \
0                          D P S S      D             P             S
1      G R G R S R S R S G R G S R      G             R             G
2                          S G G G      S             G             G
3                        G G D P D      G             G             D
4                        G R S R D      G             R             S
..                             ...    ...    ...    ...    ...    ...    ...
289                      P G G R S      P             G             G
290                    S R S G R S      S             R             S
291      S P D S R G S D P G R S R      S             P             D
292              G G G R G P G P P      G             G             G
293  G G P P D P D S D S R S G R S      G             G             P

    Note_7 Note_8 Note_9  ... Note_22 Note_23 Note_24 Note_25 Note_26 Note_27  \
0        S      S      S  ...       S       S       S       S       S       S
1        R             S  ...               G               S               R
2        G                ...
3        P             D  ...
4        R             D  ...       D       D       D       D       D       D
..     ...    ...    ...  ...     ...     ...     ...     ...     ...     ...
289      R             S  ...       G       G       G       G       G       G
290      G             R  ...       S       S       S       S       S       S
291      S             R  ...               S               R
292      R             G  ...
293      P             D  ...               S               G               R

    Note_28 Note_29 Note_30 Note_31
0         S       S       S       S
1         R       R       R       R
2
3
4         D       D       D       D
..      ...     ...     ...     ...
289       G       G       G       G
290       S       S       S       S
291
292
293               S       P       P

[294 rows x 32 columns]

In [ ]:
result.head()

,Notes,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,...,Note_22,Note_23,Note_24,Note_25,Note_26,Note_27,Note_28,Note_29,Note_30,Note_31
0,D P S S,D,,P,,S,,S,S,S,...,S,S,S,S,S,S,S,S,S,S
1,G R G R S R S R S G R G S R,G,,R,,G,,R,,S,...,,G,,S,,R,R,R,R,R
2,S G G G,S,,G,,G,,G,,,...,,,,,,,,,,
3,G G D P D,G,,G,,D,,P,,D,...,,,,,,,,,,
4,G R S R D,G,,R,,S,,R,,D,...,D,D,D,D,D,D,D,D,D,D

In [ ]:
result = pd.concat([result] * 7, ignore_index=True)

print(result)

In [ ]:
# shuffle the values within each row
for i in range(len(result)):
  if(i%7 == 0):
    np.random.shuffle(result.iloc[i].values)

print(result)

In [ ]:
from google.colab import files
result.to_csv('result.csv', encoding = 'utf-8-sig') 
files.download('result.csv')

## Generation of fourth form is complete.

Here we split the notes given in the dataset into different columns. Following this, I included a shuffle option so that the dataset doesnt have similar kind of lyrical notes cluttered in a single zone.

This has absolutely no effect on the dataset anyway.

## Fifth Iteration

Here is where the actual dataset slowly starts to take shape.

In [ ]:
result = pd.read_csv('/content/result.csv')
result.head()

,Notes,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,...,Note_17,Note_18,Note_19,Note_20,Note_21,Note_22,Note_23,Note_24,Note_25,Note_26
0,D P S S,D,P,S,S,D,P,S,S,D,...,S,S,D,P,S,S,S,D,D,P
1,G R G R S R S R S G R G S R,G,R,G,R,G,R,G,R,G,...,G,R,G,R,G,R,S,G,G,R
2,S G G G,S,G,G,G,S,G,G,G,S,...,G,G,S,G,G,G,S,S,S,G
3,G G D P D,G,G,D,P,G,G,D,P,G,...,D,P,G,G,D,P,D,G,G,G
4,G R S R D,G,R,S,R,G,R,S,R,G,...,S,R,G,R,S,R,D,G,G,R

### Below function maps the notes to their respective frequencies as per the piano format.

Python is pretty durable; however I did use some Excel to speed up my preprocessing as I was short of time.

In [ ]:
import pandas as pd
import numpy as np

# Define the mapping
mapping = {
    'D': [110, 220],
    'S': [130.81, 261.63],
    'R': [146.83, 293.66],
    'G': [164.81, 329.63],
    'P': [196]
}

# Replace D, S, R, G, and P with their mapping values
for col in result.columns:
    result[col] = result[col].apply(lambda x: [np.random.choice(mapping[i]) for i in x.split()] if type(x) == str else x)

# Convert the list of lists to a dataframe
df3 = pd.DataFrame(df3.to_dict(orient='list'))

### I found median of the all the notes and stored it as another column you see

In [ ]:
copyres = pd.read_csv('/content/copyres.csv')
copyres.head()

,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,Note_10,...,Note_18,Note_19,Note_20,Note_21,Note_22,Note_23,Note_24,Note_25,Note_26,Median
0,110.00,196.00,261.63,130.81,110.00,196.00,130.81,261.63,220.00,196.00,...,130.81,220.00,196.00,261.63,261.63,130.81,220.00,110.00,196.00,196.00
1,329.63,293.66,164.81,293.66,329.63,293.66,329.63,293.66,164.81,293.66,...,293.66,329.63,293.66,164.81,146.83,130.81,164.81,329.63,146.83,293.66
2,130.81,329.63,329.63,329.63,261.63,329.63,164.81,164.81,261.63,164.81,...,329.63,261.63,329.63,329.63,329.63,261.63,130.81,261.63,164.81,261.63
3,164.81,329.63,110.00,196.00,329.63,164.81,110.00,196.00,329.63,329.63,...,196.00,329.63,329.63,220.00,196.00,110,164.81,164.81,329.63,208.00
4,164.81,293.66,261.63,146.83,329.63,293.66,261.63,146.83,164.81,146.83,...,146.83,329.63,146.83,130.81,293.66,220,329.63,164.81,146.83,164.81

### Here is the main crux of all the struggle I went through so far.

I found the median; and then i try to find the closest note frequency to the median. That will be our target variable for ML model we are going to implement.

In [ ]:
import numpy as np
import pandas as pd

# Define the mapping
mapping = {
    'D': [110, 220],
    'S': [130.81, 261.63],
    'R': [146.83, 293.66],
    'G': [164.81, 329.63],
    'P': [196]
}


# Define a function to find the closest note for each row
def find_closest_note(row):
    median = row['Median']
    closest_note = ''
    closest_distance = np.inf
    for note, values in mapping.items():
        for value in values:
            distance = abs(median - value)
            if distance < closest_distance:
                closest_note = note
                closest_distance = distance
    return closest_note

# Apply the function to the dataset and create a new column
copyres['closest_note'] = copyres.apply(find_closest_note, axis=1)

# Print the updated dataset
print(copyres)

In [ ]:
from google.colab import files
copyres.to_csv('res.csv', encoding = 'utf-8-sig') 
files.download('res.csv')

## Generation of fifth form is complete.

It took 5 rounds of evolution to reach its current stage.

## Final form

The dataset you know and love.

In [ ]:
res = pd.read_csv('/content/res.csv')
res.head()

,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,Note_10,...,Note_19,Note_20,Note_21,Note_22,Note_23,Note_24,Note_25,Note_26,Median,Note
0,110.00,196.00,261.63,130.81,110.00,196.00,130.81,261.63,220.00,196.00,...,220.00,196.00,261.63,261.63,130.81,220.00,110.00,196.00,196.00,P
1,329.63,293.66,164.81,293.66,329.63,293.66,329.63,293.66,164.81,293.66,...,329.63,293.66,164.81,146.83,130.81,164.81,329.63,146.83,293.66,R
2,130.81,329.63,329.63,329.63,261.63,329.63,164.81,164.81,261.63,164.81,...,261.63,329.63,329.63,329.63,261.63,130.81,261.63,164.81,261.63,S
3,164.81,329.63,110.00,196.00,329.63,164.81,110.00,196.00,329.63,329.63,...,329.63,329.63,220.00,196.00,110,164.81,164.81,329.63,208.00,D
4,164.81,293.66,261.63,146.83,329.63,293.66,261.63,146.83,164.81,146.83,...,329.63,146.83,130.81,293.66,220,329.63,164.81,146.83,164.81,G