## PART 2 - MINING AND CLASSIFICATION

In [ ]:
!pip install mlxtend
!pip install prefixspan

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.9/dist-packages (0.14.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.22.4)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.10.1)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.2.2)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (1.4.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from mlxtend) (67.6.1)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.9/dist-packages (from mlxtend) (3.7.1)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (5.12.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.0.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (8.4.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (4.39.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=1.5.1->mlxtend) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.17.1->mlxtend) (2022.7.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.18->mlxtend) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.18->mlxtend) (3.1.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=3.2.0->matplotlib>=1.5.1->mlxtend) (3.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib>=1.5.1->mlxtend) (1.16.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting prefixspan
  Downloading prefixspan-0.5.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting docopt>=0.6.2
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting extratools>=0.8.1
  Downloading extratools-0.8.2.1.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: sortedcontainers>=1.5.10 in /usr/local/lib/python3.9/dist-packages (from extratools>=0.8.1->prefixspan) (2.4.0)
Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from extratools>=0.8.1->prefixspan) (0.12.0)
Building wheels for collected packages: prefixspan, docopt, extratools
  Building wheel for prefixspan (setup.py) ... done
  Created wheel for prefixspan: filename=prefixspan-0.5.2-py3-none-any.whl size=11239 sha256=fab39cabb00352917f2e50ac9f650206f1099677bacf83d48c1bbc40d157f013
  Stored in directory: /root/.cache/pip/wheels/1b/96/e2/4eafa983829d97cbdd88d66b06221e28a35ff5b8c618c9910d
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13721 sha256=2f54b299b3df96c291a8ce3f9bc44c78ebf9313a02c620f240ade3073b782d92
  Stored in directory: /root/.cache/pip/wheels/70/4a/46/1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
  Building wheel for extratools (setup.py) ... done
  Created wheel for extratools: filename=extratools-0.8.2.1-py3-none-any.whl size=28884 sha256=203439547bb0c610e0658105151a87ffb25beb9ffc747af25e234eefec38d9ca
  Stored in directory: /root/.cache/pip/wheels/70/da/ea/30cdb9e0582afe1366c233eb955481c3676edc00249844295c
Successfully built prefixspan docopt extratools
Installing collected packages: docopt, extratools, prefixspan
Successfully installed docopt-0.6.2 extratools-0.8.2.1 prefixspan-0.5.2

In [ ]:
# import necessary libraries
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

data = pd.read_csv('/content/res (1).csv')
data.head()

,110,196,261.63,130.81,110.1,196.1,130.81.1,261.63.1,220,196.2,...,220.1,196.4,261.63.3,261.63.4,130.81.7,220.2,110.3,196.5,196.6,P
0,329.63,293.66,164.81,293.66,329.63,293.66,329.63,293.66,164.81,293.66,...,329.63,293.66,164.81,146.83,130.81,164.81,329.63,146.83,293.66,R
1,130.81,329.63,329.63,329.63,261.63,329.63,164.81,164.81,261.63,164.81,...,261.63,329.63,329.63,329.63,261.63,130.81,261.63,164.81,261.63,S
2,164.81,329.63,110.00,196.00,329.63,164.81,110.00,196.00,329.63,329.63,...,329.63,329.63,220.00,196.00,110,164.81,164.81,329.63,208.00,D
3,164.81,293.66,261.63,146.83,329.63,293.66,261.63,146.83,164.81,146.83,...,329.63,146.83,130.81,293.66,220,329.63,164.81,146.83,164.81,G
4,130.81,130.81,261.63,293.66,130.81,130.81,130.81,146.83,261.63,130.81,...,261.63,261.63,130.81,146.83,146.83,130.81,261.63,261.63,204.23,P

### (1) Data Mining Algorithm

I am planning to use PrefixSpan algorithm

### Apriori

In [ ]:
# Import the PrefixSpan algorithm from the prefixspan library
from prefixspan import PrefixSpan

In [ ]:
df = pd.read_csv('/content/df2 (1).csv')
df.head()

                                   D', 'P', 'S', 'S'
0  G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G...
1                                  S', 'G', 'G', 'G'
2                             G', 'G', 'D', 'P', 'D'
3                             G', 'R', 'S', 'R', 'D'
4  S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D...

In [ ]:
# convert to list using tolist()
df_list = df.values.tolist()
print(df_list)

[["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["S', 'G', 'G', 'G'"], ["G', 'G', 'D', 'P', 'D'"], ["G', 'R', 'S', 'R', 'D'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["G', 'R', 'S', 'R', 'D'"], ["G', 'G', 'D', 'P', 'G'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'G', 'G', 'G'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["P', 'G', 'G', 'R', 'S'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"], ["D', 'P', 'G', 'G', 'R'"], ["P', 'G', 'P', 'P'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["G', 'G', 'P', 'P'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["G', 'G', 'D', 'P', 'G'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["G', 'G', 'D', 'P', 'G'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'G', 'G', 'G', 'R'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["G', 'G', 'D', 'P', 'D'"], ["R', 'S', 'D', 'D', 'P'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["P', 'G', 'P', 'P'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["S', 'G', 'G', 'G'"], ["D', 'P', 'S', 'S'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["R', 'S', 'D', 'D', 'P'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"], ["G', 'P', 'D', 'S', 'D'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["D', 'P', 'S', 'S'"], ["G', 'R', 'P', 'G', 'R'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["S', 'G', 'G', 'G'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["D', 'G', 'R', 'R', 'S'"], ["R', 'S', 'D', 'D', 'P'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["P', 'G', 'P', 'P'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["G', 'G', 'P', 'P'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'S', 'S'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["P', 'G', 'G', 'R', 'S'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'P', 'D', 'S', 'D'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["G', 'G', 'G', 'G', 'R'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["G', 'G', 'P', 'P'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'R', 'P', 'G', 'R'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["G', 'G', 'P', 'P'"], ["R', 'S', 'D', 'D', 'P'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'R', 'S', 'R', 'D'"], ["G', 'R', 'P', 'G', 'R'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["S', 'G', 'G', 'G'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'P', 'D', 'S', 'D'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'S', 'S'"], ["D', 'G', 'R', 'R', 'S'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["G', 'G', 'D', 'P', 'D'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'G', 'G', 'R'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["P', 'G', 'P', 'P'"], ["G', 'G', 'P', 'P'"], ["D', 'P', 'S', 'S'"], ["S', 'G', 'G', 'G'"], ["D', 'P', 'S', 'S'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["G', 'G', 'D', 'P', 'D'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["G', 'P', 'D', 'S', 'D'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"], ["S', 'G', 'G', 'G'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["D', 'P', 'G', 'G', 'R'"], ["D', 'P', 'G', 'G', 'R'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["G', 'G', 'P', 'P'"], ["D', 'G', 'R', 'R', 'S'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["P', 'G', 'G', 'R', 'S'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'R', 'S', 'R', 'D'"], ["R', 'S', 'D', 'D', 'P'"], ["G', 'G', 'G', 'G', 'R'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["D', 'G', 'R', 'R', 'S'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["G', 'G', 'P', 'P'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["R', 'S', 'D', 'D', 'P'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'R', 'P', 'G', 'R'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["R', 'S', 'D', 'D', 'P'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["G', 'R', 'S', 'R', 'D'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["P', 'G', 'G', 'R', 'S'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["D', 'P', 'S', 'S'"], ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"], ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"], ["G', 'G', 'D', 'P', 'G'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["G', 'R', 'P', 'G', 'R'"], ["G', 'P', 'D', 'S', 'D'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"], ["G', 'P', 'D', 'S', 'D'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'G', 'R', 'R', 'S'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["G', 'R', 'S', 'R', 'D'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'D', 'P', 'D'"], ["D', 'P', 'S', 'S'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["G', 'G', 'D', 'P', 'G'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'S', 'S'"], ["G', 'R', 'P', 'G', 'R'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"], ["D', 'S', 'D', 'D', 'D', 'P'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"], ["G', 'G', 'D', 'P', 'D'"], ["G', 'G', 'D', 'P', 'G'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["D', 'G', 'R', 'R', 'S'"], ["G', 'G', 'G', 'G', 'R'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["D', 'P', 'S', 'S'"], ["D', 'P', 'G', 'G', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'S', 'S'"], ["G', 'P', 'D', 'S', 'D'"], ["P', 'G', 'G', 'R', 'S'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["D', 'P', 'S', 'S'"], ["G', 'G', 'D', 'P', 'G'"], ["P', 'G', 'G', 'R', 'S'"], ["R', 'D', 'S', 'R', 'G', 'R'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["G', 'G', 'G', 'G', 'R'"], ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"], ["G', 'G', 'G', 'G', 'R'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["P', 'G', 'P', 'P'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["P', 'G', 'P', 'P'"], ["P', 'G', 'P', 'P'"], ["G', 'R', 'P', 'G', 'R'"], ["D', 'P', 'S', 'S'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["G', 'G', 'D', 'P', 'D'"], ["D', 'P', 'G', 'G', 'R'"], ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"], ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"], ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"], ["G', 'R', 'S', 'R', 'D'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'G', 'R', 'R', 'S'"], ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'G', 'G', 'R', 'S'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"], ["D', 'P', 'G', 'G', 'R'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"], ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"], ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"], ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"], ["P', 'G', 'G', 'R', 'S'"], ["S', 'R', 'S', 'G', 'R', 'S'"], ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"], ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"], ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"]]

In [ ]:
# Create an instance of the PrefixSpan algorithm
ps = PrefixSpan(df_list)

# Find frequent sequential patterns with a minimum support of 2
patterns = ps.frequent(2)

# Print the frequent sequential patterns
for pattern in patterns:
    print(pattern)

(7, ["G', 'R', 'G', 'R', 'S', 'R', 'S', 'R', 'S', 'G', 'R', 'G', 'S', 'R'"])
(7, ["S', 'G', 'G', 'G'"])
(7, ["G', 'G', 'D', 'P', 'D'"])
(7, ["G', 'R', 'S', 'R', 'D'"])
(7, ["S', 'S', 'S', 'R', 'R', 'G', 'G', 'P', 'P', 'D', 'D'"])
(7, ["G', 'P', 'G', 'G', 'R', 'S', 'R', 'G', 'R', 'R', 'S', 'D', 'S', 'R', 'G', 'R'"])
(7, ["G', 'G', 'D', 'P', 'G'"])
(7, ["G', 'G', 'D', 'D', 'P', 'G', 'G', 'D', 'P', 'G', 'P', 'G', 'R', 'S', 'R'"])
(7, ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'R', 'G', 'P', 'G', 'R', 'S', 'R'"])
(7, ["R', 'D', 'S', 'R', 'G', 'R'"])
(7, ["D', 'S', 'R', 'S', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"])
(7, ["G', 'P', 'D', 'P', 'D', 'S', 'R', 'G', 'R', 'G', 'S', 'R', 'D'"])
(14, ["D', 'P', 'G', 'G', 'R'"])
(7, ["G', 'G', 'R', 'S', 'S', 'R', 'R', 'G', 'G', 'R', 'R'"])
(7, ["D', 'S', 'D', 'D', 'D', 'P'"])
(7, ["G', 'G', 'P', 'P', 'D', 'P', 'D', 'S', 'D', 'S', 'R', 'S', 'G', 'R', 'S'"])
(7, ["G', 'G', 'R', 'G', 'R', 'S', 'R', 'G', 'G', 'P', 'D', 'D', 'S', 'R'"])
(7, ["P', 'G', 'G', 'R', 'S'"])
(7, ["S', 'R', 'G', 'R', 'S', 'R', 'S', 'D', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"])
(7, ["P', 'D', 'D', 'P', 'G', 'R', 'S', 'R', 'G', 'R', 'S', 'D'"])
(7, ["P', 'G', 'P', 'P'"])
(7, ["G', 'G', 'P', 'P'"])
(7, ["G', 'P', 'G', 'P', 'D', 'P', 'D', 'S', 'D', 'P', 'G', 'D', 'P', 'G', 'R'"])
(7, ["S', 'D', 'S', 'R', 'G', 'R', 'G', 'P', 'G', 'P', 'D', 'P'"])
(7, ["S', 'R', 'G', 'R', 'G', 'R', 'D', 'S', 'R', 'S', 'R', 'S', 'P', 'D', 'S', 'D'"])
(7, ["D', 'S', 'D', 'D', 'P', 'G', 'D', 'P', 'D', 'G', 'D', 'P', 'G', 'R', 'S', 'R'"])
(7, ["G', 'G', 'P', 'G', 'G', 'P', 'P', 'D', 'D', 'P'"])
(14, ["G', 'P', 'D', 'S', 'D'"])
(7, ["G', 'G', 'G', 'G', 'R'"])
(7, ["S', 'R', 'G', 'P', 'D', 'S', 'S', 'D', 'P', 'G', 'R'"])
(7, ["R', 'S', 'D', 'D', 'P'"])
(7, ["G', 'G', 'G', 'D', 'P', 'G', 'R', 'G', 'G', 'S', 'D', 'P', 'G', 'R'"])
(7, ["D', 'P', 'G', 'G', 'R', 'S'"])
(13, ["D', 'P', 'S', 'S'"])
(7, ["S', 'R', 'S', 'G', 'R', 'S'"])
(7, ["G', 'R', 'P', 'G', 'R'"])
(7, ["D', 'G', 'R', 'R', 'S'"])
(7, ["G', 'G', 'G', 'R', 'G', 'P', 'G', 'P', 'P'"])
(7, ["S', 'P', 'D', 'S', 'R', 'G', 'S', 'D', 'P', 'G', 'R', 'S', 'R'"])

(2) Classification algorithm

SVM Algorithm

In [ ]:
# Import the necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Load the dataset into a pandas DataFrame
import pandas as pd
data = pd.read_csv('/content/res.csv',header = 0)

data.head()

,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,Note_10,...,Note_18,Note_19,Note_20,Note_21,Note_22,Note_23,Note_24,Note_25,Note_26,Note
0,110.00,196.00,261.63,130.81,110.00,196.00,130.81,261.63,220.00,196.00,...,130.81,220.00,196.00,261.63,261.63,130.81,220.00,110.00,196.00,P
1,329.63,293.66,164.81,293.66,329.63,293.66,329.63,293.66,164.81,293.66,...,293.66,329.63,293.66,164.81,146.83,130.81,164.81,329.63,146.83,R
2,130.81,329.63,329.63,329.63,261.63,329.63,164.81,164.81,261.63,164.81,...,329.63,261.63,329.63,329.63,329.63,261.63,130.81,261.63,164.81,S
3,164.81,329.63,110.00,196.00,329.63,164.81,110.00,196.00,329.63,329.63,...,196.00,329.63,329.63,220.00,196.00,110.00,164.81,164.81,329.63,D
4,164.81,293.66,261.63,146.83,329.63,293.66,261.63,146.83,164.81,146.83,...,146.83,329.63,146.83,130.81,293.66,220.00,329.63,164.81,146.83,G

In [ ]:
type(data["Note"])

pandas.core.series.Series

In [ ]:
# Replace missing values with the mean value of the column
data = data.fillna(data.mean())

<ipython-input-29-85f7bc2b9a1e>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data = data.fillna(data.mean())

In [ ]:
data.head()

,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,Note_10,...,Note_18,Note_19,Note_20,Note_21,Note_22,Note_23,Note_24,Note_25,Note_26,Note
0,110.00,196.00,261.63,130.81,110.00,196.00,130.81,261.63,220.00,196.00,...,130.81,220.00,196.00,261.63,261.63,130.81,220.00,110.00,196.00,P
1,329.63,293.66,164.81,293.66,329.63,293.66,329.63,293.66,164.81,293.66,...,293.66,329.63,293.66,164.81,146.83,130.81,164.81,329.63,146.83,R
2,130.81,329.63,329.63,329.63,261.63,329.63,164.81,164.81,261.63,164.81,...,329.63,261.63,329.63,329.63,329.63,261.63,130.81,261.63,164.81,S
3,164.81,329.63,110.00,196.00,329.63,164.81,110.00,196.00,329.63,329.63,...,196.00,329.63,329.63,220.00,196.00,110.00,164.81,164.81,329.63,D
4,164.81,293.66,261.63,146.83,329.63,293.66,261.63,146.83,164.81,146.83,...,146.83,329.63,146.83,130.81,293.66,220.00,329.63,164.81,146.83,G

In [ ]:
# Replace empty spaces and null values with NaN
data = data.replace(r'^\s*$', np.nan, regex=True)
data = data.dropna()

# Replace remaining null values with column median
data = data.fillna(data.median())

# Print the updated dataset
print(data)

     Note_1  Note_2  Note_3  Note_4  Note_5  Note_6  Note_7  Note_8  Note_9  \
0    110.00  196.00  261.63  130.81  110.00  196.00  130.81  261.63  220.00
1    329.63  293.66  164.81  293.66  329.63  293.66  329.63  293.66  164.81
2    130.81  329.63  329.63  329.63  261.63  329.63  164.81  164.81  261.63
3    164.81  329.63  110.00  196.00  329.63  164.81  110.00  196.00  329.63
4    164.81  293.66  261.63  146.83  329.63  293.66  261.63  146.83  164.81
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
260  261.63  196.00  110.00  130.81  130.81  196.00  110.00  130.81  130.81
261  220.00  196.00  164.81  164.81  220.00  196.00  329.63  329.63  220.00
262  110.00  196.00  164.81  329.63  110.00  196.00  164.81  329.63  220.00
263  329.63  164.81  293.66  261.63  329.63  329.63  146.83  130.81  164.81
264  110.00  261.63  220.00  110.00  220.00  130.81  220.00  220.00  110.00

     Note_10  ...  Note_18  Note_19  Note_20  Note_21  Note_22  Note_23  \
0     196.00  ...   130.81   220.00   196.00   261.63   261.63   130.81
1     293.66  ...   293.66   329.63   293.66   164.81   146.83   130.81
2     164.81  ...   329.63   261.63   329.63   329.63   329.63   261.63
3     329.63  ...   196.00   329.63   329.63   220.00   196.00   110.00
4     146.83  ...   146.83   329.63   146.83   130.81   293.66   220.00
..       ...  ...      ...      ...      ...      ...      ...      ...
260   196.00  ...   261.63   261.63   196.00   110.00   261.63   293.66
261   196.00  ...   164.81   220.00   196.00   164.81   329.63   146.83
262   196.00  ...   329.63   110.00   196.00   329.63   164.81   293.66
263   329.63  ...   261.63   164.81   164.81   293.66   261.63   261.63
264   261.63  ...   110.00   110.00   261.63   220.00   110.00   196.00

     Note_24  Note_25  Note_26  Note
0     220.00   110.00   196.00     P
1     164.81   329.63   146.83     R
2     130.81   261.63   164.81     S
3     164.81   164.81   329.63     D
4     329.63   164.81   146.83     G
..       ...      ...      ...   ...
260   261.63   130.81   196.00     P
261   220.00   220.00   196.00     P
262   220.00   110.00   196.00     P
263   329.63   329.63   329.63     S
264   220.00   220.00   261.63     D

[252 rows x 27 columns]

<ipython-input-31-c6e5a709fb4c>:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data = data.fillna(data.median())

In [ ]:
data.shape

(252, 27)

In [ ]:
data = pd.concat([data] * 7, ignore_index=True)

data.shape

(1764, 27)

In [ ]:
# shuffle the values within each row
for i in range(len(data)):
  if(i%3 == 0):
    np.random.shuffle(data.iloc[i].values)

data.head()

,Note_1,Note_2,Note_3,Note_4,Note_5,Note_6,Note_7,Note_8,Note_9,Note_10,...,Note_18,Note_19,Note_20,Note_21,Note_22,Note_23,Note_24,Note_25,Note_26,Note
0,110.00,196.00,261.63,130.81,110.00,196.00,130.81,261.63,220.00,196.00,...,130.81,220.00,196.00,261.63,261.63,130.81,220.00,110.00,196.00,P
1,329.63,293.66,164.81,293.66,329.63,293.66,329.63,293.66,164.81,293.66,...,293.66,329.63,293.66,164.81,146.83,130.81,164.81,329.63,146.83,R
2,130.81,329.63,329.63,329.63,261.63,329.63,164.81,164.81,261.63,164.81,...,329.63,261.63,329.63,329.63,329.63,261.63,130.81,261.63,164.81,S
3,164.81,329.63,110.00,196.00,329.63,164.81,110.00,196.00,329.63,329.63,...,196.00,329.63,329.63,220.00,196.00,110.00,164.81,164.81,329.63,D
4,164.81,293.66,261.63,146.83,329.63,293.66,261.63,146.83,164.81,146.83,...,146.83,329.63,146.83,130.81,293.66,220.00,329.63,164.81,146.83,G

In [ ]:
# Convert the "Note" column into numeric format
le = LabelEncoder()
data["Note"] = le.fit_transform(data["Note"])

In [ ]:
# Split the dataset into training and testing sets
x = data.iloc[:, :-1]
y = data.iloc[:, -1]
x = np.array(x)
y = np.array(y)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier


# create a list of classifiers
classifiers = [
    DecisionTreeClassifier(random_state=42),
    RandomForestClassifier(random_state=42),
    GradientBoostingClassifier(random_state = 42),
    MLPClassifier(random_state = 42),
    SVC(random_state=42)

]

# iterate over classifiers and fit them to the training data
for clf in classifiers:
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print("Classifier:", clf.__class__.__name__)
    print("Classification Report - None Average")
    print(classification_report(y_test, y_pred))

Classifier: DecisionTreeClassifier
Classification Report - None Average
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       117
           1       1.00      1.00      1.00       141
           2       1.00      1.00      1.00       293
           3       1.00      1.00      1.00        77
           4       1.00      1.00      1.00        78

    accuracy                           1.00       706
   macro avg       1.00      1.00      1.00       706
weighted avg       1.00      1.00      1.00       706

Classifier: RandomForestClassifier
Classification Report - None Average
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       117
           1       1.00      1.00      1.00       141
           2       1.00      1.00      1.00       293
           3       1.00      1.00      1.00        77
           4       1.00      1.00      1.00        78

    accuracy                           1.00       706
   macro avg       1.00      1.00      1.00       706
weighted avg       1.00      1.00      1.00       706

Classifier: GradientBoostingClassifier
Classification Report - None Average
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       117
           1       1.00      1.00      1.00       141
           2       1.00      1.00      1.00       293
           3       1.00      1.00      1.00        77
           4       1.00      1.00      1.00        78

    accuracy                           1.00       706
   macro avg       1.00      1.00      1.00       706
weighted avg       1.00      1.00      1.00       706

Classifier: MLPClassifier
Classification Report - None Average
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       117
           1       1.00      1.00      1.00       141
           2       0.96      1.00      0.98       293
           3       1.00      0.84      0.92        77
           4       1.00      1.00      1.00        78

    accuracy                           0.98       706
   macro avg       0.99      0.97      0.98       706
weighted avg       0.98      0.98      0.98       706

Classifier: SVC
Classification Report - None Average
              precision    recall  f1-score   support

           0       1.00      0.93      0.96       117
           1       1.00      1.00      1.00       141
           2       0.97      1.00      0.99       293
           3       1.00      1.00      1.00        77
           4       1.00      1.00      1.00        78

    accuracy                           0.99       706
   macro avg       0.99      0.99      0.99       706
weighted avg       0.99      0.99      0.99       706

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### All evaluation metrics : 1? 😯

For a dataset built from scratch?